version: "3.3"

services:
  db:
    image: mongo:latest
    networks:
      - api_net
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  api:
    image: autonomouse/api:latest
    ports:
      - "80:3000"
    networks:
      - api_net
    environment:
      - DB_URL=mongodb://db:27017
      - DEBUG=app:*

networks:
  api_net:

volumes:
  dbdata:
